#!/bin/bash

. /home/pi/gosurf_logger.sh

log "starting..."

PICTURE_SLEEP=1700
PICTURE_DURATION=13200 #1700 * 8

export PICTURE_OUTPUT_DIR=/tmp/gosurf/
PICTURE_OUTPUT_FILE=gosurf_pic_%02d.jpg

log "PICTURE SLEEP=$PICTURE_SLEEP"
log "PICTURE DURATION=$PICTURE_DURATION"
log "PICTURE OUTPUTS=$PICTURE_OUTPUT_DIR/$PICTURE_OUTPUT_FILE"

log `rm -rf $PICTURES_OUTPUT_DIR 2>&1`
log `mkdir -p $PICTURE_OUTPUT_DIR 2>&1`

log `raspistill -n -tl $PICTURE_SLEEP -t $PICTURE_DURATION -o $PICTURE_OUTPUT_DIR/$PICTURE_OUTPUT_FILE 2>&1`
